/* ----------------------------------------------------------
    PLANIFICACIÓN E INTEGRIDAD DE DATOS HISTÓRICOS
    OBJETIVO: Consolidar la estructura académica y detectar anomalías
    ENTORNO: Oracle Live SQL (Esquema AD)
    ----------------------------------------------------------
*/

-- 1. CONSOLIDACIÓN MAESTRA DE INFORMACIÓN (VISTA 360)
-- Genera una matriz completa que vincula periodos, áreas, jefaturas y docentes.
CREATE OR REPLACE VIEW V_CONSOLIDADO_ACADEMICO_TOTAL AS
SELECT 
    per.SESSION_ID AS "ID_PERIODO",
    dep.DEPARTMENT_NAME AS "DEPARTAMENTO",
    dep.HOD AS "RESPONSABLE_AREA",
    cur.COURSE_NAME AS "ASIGNATURA",
    fac.FIRST_NAME || ' ' || fac.LAST_NAME AS "DOCENTE_TITULAR",
    fac.EMAIL AS "CORREO_CONTACTO"
FROM 
    AD.AD_ACADEMIC_SESSION per
JOIN 
    AD.AD_COURSE_DETAILS cur ON per.SESSION_ID = cur.SESSION_ID
LEFT JOIN 
    AD.AD_DEPARTMENTS dep ON cur.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT JOIN 
    AD.AD_FACULTY_COURSE_DETAILS fc ON cur.COURSE_ID = fc.COURSE_ID
LEFT JOIN 
    AD.AD_FACULTY_DETAILS fac ON fc.FACULTY_ID = fac.FACULTY_ID;

-- 2. DIAGNÓSTICO DE INTEGRIDAD (DETECCIÓN DE VACÍOS)
-- Localiza inconsistencias críticas en la estructura de datos para su corrección.
SELECT 
    'CURSO SIN ASIGNACIÓN DE ÁREA' AS "TIPO_INCIDENCIA", 
    COURSE_NAME AS "ELEMENTO_AFECTADO"
FROM 
    AD.AD_COURSE_DETAILS
WHERE 
    DEPARTMENT_ID IS NULL
UNION ALL
SELECT 
    'DEPARTAMENTO SIN LIDERAZGO (HOD)' AS "TIPO_INCIDENCIA", 
    DEPARTMENT_NAME AS "ELEMENTO_AFECTADO"
FROM 
    AD.AD_DEPARTMENTS
WHERE 
    HOD IS NULL;

-- 3. CONTROL DE REDUNDANCIA (DUPLICADOS)
-- Identificación de registros repetidos que pueden alterar las estadísticas del periodo.
SELECT 
    COURSE_NAME AS "CURSO_REPETIDO", 
    SESSION_ID AS "PERIODO_ID", 
    COUNT(COURSE_ID) AS "NUMERO_DE_REGISTROS"
FROM 
    AD.AD_COURSE_DETAILS
GROUP BY 
    COURSE_NAME, SESSION_ID
HAVING 
    COUNT(COURSE_ID) > 1;

-- 4. ANÁLISIS DE FORTALECIMIENTO INSTITUCIONAL
-- Determina qué áreas requieren mayor oferta académica basándose en el volumen actual.
SELECT 
    d.DEPARTMENT_NAME AS "FACULTAD_DEPARTAMENTO", 
    COUNT(c.COURSE_ID) AS "OFERTA_ACTUAL"
FROM 
    AD.AD_DEPARTMENTS d
LEFT JOIN 
    AD.AD_COURSE_DETAILS c ON d.DEPARTMENT_ID = c.DEPARTMENT_ID
GROUP BY 
    d.DEPARTMENT_NAME
ORDER BY 
    "OFERTA_ACTUAL" ASC;

-- 5. PROYECCIÓN DE CARGA ESTUDIANTIL (PREPARACIÓN NUEVA TEMPORADA)
-- Evaluación de la relación Alumno-Docente para la planificación del nuevo ciclo.
SELECT 
    c.COURSE_NAME AS "MATERIA", 
    f.FIRST_NAME || ' ' || f.LAST_NAME AS "DOCENTE_A_CARGO", 
    COUNT(sc.STUDENT_ID) AS "TOTAL_INSCRITOS"
FROM 
    AD.AD_COURSE_DETAILS c
LEFT JOIN 
    AD.AD_STUDENT_COURSE_DETAILS sc ON c.COURSE_ID = sc.COURSE_ID
LEFT JOIN 
    AD.AD_FACULTY_COURSE_DETAILS fc ON c.COURSE_ID = fc.COURSE_ID
LEFT JOIN 
    AD.AD_FACULTY_DETAILS f ON fc.FACULTY_ID = f.FACULTY_ID
GROUP BY 
    c.COURSE_NAME, 
    f.FIRST_NAME, 
    f.LAST_NAME
ORDER BY 
    "TOTAL_INSCRITOS" DESC;
